[package]
name = "filter-ref"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { workspace = true }
eyre = { workspace = true }
log = { workspace = true }
env_logger = { workspace = true }
git2 = "0.18.3"
chrono = "0.4.38"

