[package]
name = "filter-ref"
version = "0.1.13"
edition = "2021"
build = "../build.rs"

[dependencies]
clap = { workspace = true }
eyre = { workspace = true }
log = { workspace = true }
env_logger = { workspace = true }
git2 = { workspace = true }
chrono = "0.4.41"
