[package]
name = "ls-github-repos"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { workspace = true }
eyre = { workspace = true }
log = { workspace = true }
env_logger = { workspace = true }

reqwest = { version = "0.12.4", features = ["json"] }
serde_json = "1.0.116"
shellexpand = "3.1.0"
tokio = { version = "1.37.0", features = ["full"] }
