[package]
name = "ls-github-repos"
version = "0.1.12"
edition = "2021"
build = "../build.rs"

[dependencies]
clap = { workspace = true }
eyre = { workspace = true }
log = { workspace = true }
env_logger = { workspace = true }

reqwest = { version = "0.12.12", features = ["json"] }
serde_json = "1.0.135"
shellexpand = "3.1.0"
tokio = { version = "1.43.0", features = ["full"] }
