[package]
name = "reposlug"
version = "0.1.13"
edition = "2021"
build = "build.rs"

[dependencies]
clap = { workspace = true }
eyre = { workspace = true }
log = { workspace = true }
env_logger = { workspace = true }
git2 = { workspace = true }
regex = "1.11.1"
url = "2.5.4"
