[package]
name = "reposlug"
version = "0.1.0"
edition = "2021"
build = "../build.rs"

[dependencies]
clap = { workspace = true }
eyre = { workspace = true }
log = { workspace = true }
env_logger = { workspace = true }
git2 = "0.18.3"
regex = "1.10.4"
url = "2.5.0"

