[package]
name = "common"
version = "0.1.0"
edition = "2021"

[dependencies]
eyre = { workspace = true }
regex = "1.11.1"
git2 = { workspace = true }
serde = { version = "1.0", features = ["derive"] }

[dev-dependencies]
tempfile = "3.20" 
